#!/usr/bin/env python3
"""
RFuzz 2FSK decode / regenerate tools.

Decode: turn a raw CC1101 GDO2 capture (capture_custom.py .raw, 1 byte/sample,
bit0=GDO0, bit1=GDO2) into a cleaned, quantized bitstream and locate packets
(preamble 0xAA + sync 0xDEAF + 4-byte payload, MSB-first; preamble length is
configurable via --preamble, default 4 bytes).

Regen: re-modulate the decoded packets back to 2FSK I/Q int8 (.c8) so the
on-antenna signal can be loaded into URH and compared against the original
TX file (rfuzz_2fsk.c8, generated by gen_2fsk.py).

Modulation constants match gen_2fsk.py:
    FS=2.4 MS/s, BPS=2400, DEV=50 kHz, AMP=90 (int8), phase-continuous.

Note on sample rate: the firmware computes the timer alarm as
`1000000 / requested` (integer), so requesting 48000 Hz actually runs at
50000 Hz. This tool derives the real rate automatically unless --spb is given.

Usage:
    python rfuzz_tools.py decode --raw capture.raw --rate 48000
    python rfuzz_tools.py regen  --raw capture.raw --rate 48000 --out regen.c8
"""

import argparse
import sys

import numpy as np

FS = 2400000.0
BPS = 2400.0
DEFAULT_DEV = 50000.0
DEFAULT_AMP = 90
SPS = int(FS / BPS)

SYNC_BITS = np.array(
    [int(b) for b in "1101111010101111"], dtype=np.uint8
)
SYNC_BYTES = bytes([0xDE, 0xAF])
# The TX signal generator (gen_2fsk.py) sends sync 0xBEEF; SYNC_BITS above is
# the 0xDEAF word used by the legacy sniff tooling.  The multi-phase decoder
# (find_packets_multiphase) and the .sr/.vcd renderers for the rfuzz testcase
# use the real TX word - keep the legacy constants untouched for the other
# tools that depend on them.
MP_SYNC_BITS = np.array(
    [int(b) for b in "1011111011101111"], dtype=np.uint8
)
MP_SYNC_BYTES = bytes([0xBE, 0xEF])
DEFAULT_PREAMBLE_BYTES = 4
PREAMBLE_BITS = np.array([1, 0] * 16, dtype=np.uint8)
PAYLOAD_EXPECT = bytes([0x01, 0x02, 0x03, 0x04])


def preamble_bits(preamble_bytes=DEFAULT_PREAMBLE_BYTES):
    """Alternating 1/0 preamble bits (0xAA) for the given byte count."""
    return np.tile(np.array([1, 0], dtype=np.uint8), preamble_bytes * 4)


def preamble_ok(window, pre_len):
    """Check a preamble window (the pre_len bits before sync) for 0xAA.

    The CC1101 demodulator needs a few bit cells to settle bit-sync when a
    burst arrives, so the first bits can be glitchy.  The window counts as
    OK when at least 3/4 of the bits match 0xAA (random noise would match
    only ~50%, so this still rejects non-preamble regions).
    """
    if len(window) != pre_len:
        return False
    exp = np.tile(np.array([1, 0], dtype=np.uint8), pre_len // 2)
    errs = int(np.count_nonzero(window != exp))
    return errs <= pre_len // 4


def bits_msb(data):
    out = []
    for byte in data:
        out += [(byte >> i) & 1 for i in range(7, -1, -1)]
    return np.array(out, dtype=np.uint8)


def bytes_from_bits(bits):
    """Group a bit array into bytes, MSB-first (8 bits per byte)."""
    return bytes(
        int("".join(str(b) for b in bits[j:j + 8]), 2)
        for j in range(0, len(bits) - 7, 8)
    )


def actual_rate(requested):
    alarm = 1000000 // requested
    return 1000000.0 / alarm


def load_gdo2(raw_path, requested_rate):
    data = np.fromfile(raw_path, dtype=np.uint8)
    if data.size == 0:
        sys.exit("error: empty raw capture")
    ch2 = (data >> 1) & 1
    return ch2, actual_rate(requested_rate)


def load_raw(raw_path, requested_rate):
    data = np.fromfile(raw_path, dtype=np.uint8)
    if data.size == 0:
        sys.exit("error: empty raw capture")
    ch0 = data & 1
    ch1 = (data >> 1) & 1
    return ch0, ch1, actual_rate(requested_rate)


def rl_encode(bits):
    if len(bits) == 0:
        return []
    runs = []
    lvl = bits[0]
    start = 0
    for i in range(1, len(bits)):
        if bits[i] != lvl:
            runs.append((lvl, i - start))
            lvl = bits[i]
            start = i
    runs.append((lvl, len(bits) - start))
    return runs


def remove_glitches(bits, min_run):
    runs = rl_encode(bits)
    i = 1
    while i < len(runs):
        lvl, ln = runs[i]
        if ln < min_run:
            plvl, pln = runs[i - 1]
            if i + 1 < len(runs) and runs[i + 1][0] == plvl:
                runs[i - 1] = (plvl, pln + ln + runs[i + 1][1])
                del runs[i + 1]
            else:
                runs[i - 1] = (plvl, pln + ln)
            del runs[i]
        else:
            i += 1
    out = np.empty(int(sum(ln for _, ln in runs)), dtype=np.uint8)
    pos = 0
    for lvl, ln in runs:
        out[pos:pos + ln] = lvl
        pos += ln
    return out


def runs_to_bits(runs, spb):
    out = []
    for lvl, ln in runs:
        nbits = int(round(ln / spb))
        if nbits > 0:
            out += [lvl] * nbits
    return np.array(out, dtype=np.uint8)


def runs_to_bits_pos(runs, spb):
    """Run-length -> bits, also returning the raw-sample start of each bit."""
    bits = []
    starts = []
    pos = 0
    for lvl, ln in runs:
        nbits = int(round(ln / spb))
        for j in range(nbits):
            bits.append(lvl)
            starts.append(round(pos + j * spb))
        pos += ln
    return np.array(bits, dtype=np.uint8), np.array(starts, dtype=np.int64)


def majority_bits(ch2, s0, nbits, spb):
    """Decode bits by majority vote over each raw bit cell [s0+k*spb, ...)."""
    out = np.empty(nbits, dtype=np.uint8)
    for k in range(nbits):
        a = round(s0 + k * spb)
        b = round(s0 + (k + 1) * spb)
        cell = ch2[a:b]
        out[k] = 1 if cell.size and cell.sum() * 2 >= cell.size else 0
    return out


def clean_bits(ch2, spb, min_run):
    ch2 = remove_glitches(ch2, min_run)
    return runs_to_bits(rl_encode(ch2), spb)


def clean_raw_gdo2(ch1, spb, windows, glitch=10, idle=None):
    """Error-corrected raw GDO2, same length as the input (no re-encode).

    Four sample-domain corrections are applied in order:
      1. glitch filter - remove_glitches() drops sub-bit pulses (a digital
         debounce: any run shorter than `glitch` samples is merged into its
         neighbours);
      2. edge resync   - run-length encoding of the filtered stream yields a
         per-bit grid that is re-synced at every real demod edge
         (runs_to_bits_pos), so cell boundaries track the actual signal
         instead of a fixed uniform grid (the modem bit-sync compresses the
         leading bits, so a uniform grid is ~0.5-1 bit off);
      3. majority vote - every cell is re-voted over the ORIGINAL samples, so
         a glitch that only pollutes part of a cell is corrected to the true
         bit value (sub-bit errors cannot flip a cell);
      4. noise gating  - only the packet windows (from detect_datarate_iter)
         are emitted; the free-running demodulator tail between bursts (no
         carrier -> GDO2 toggles freely) is replaced with `idle` (defaults to
         the level the line holds at sample 0, so the cleaned channel idles
         exactly like the raw one).

    The result is a clean square wave whose edges sit on the real received
    edges and whose bit values are glitch-corrected - the DSP-front-end view
    of GDO2, bit-for-bit decodable (NRZ) inside each packet window.  Unlike
    GDO2_CLEAN (UART), it preserves the actual received preamble bits (the
    modem bit-sync settling) instead of substituting the ideal 0xAA.

    The .sr/.vcd probe3 GDO2_CLEAN_RAW is built on top of these corrected
    bits via clean_gdo2(..., framed=True, corrected=True) so it decodes at
    2400 baud; this NRZ form is the diagnostic used by the `clean`
    subcommand (writes <base>_clean.raw).
    """
    n = len(ch1)
    if idle is None:
        idle = int(ch1[0]) if len(ch1) else 1
    out = np.full(n, idle, dtype=np.uint8)
    g = remove_glitches(ch1, glitch)
    _qbits, qstarts = runs_to_bits_pos(rl_encode(g), spb)
    for s, e in windows:
        s = max(0, s)
        e = min(e, n)
        if e <= s:
            continue
        j = max(int(np.searchsorted(qstarts, s)) - 1, 0)
        while j < len(qstarts):
            a = max(int(qstarts[j]), s)
            if a >= e:
                break
            b = int(qstarts[j + 1]) if j + 1 < len(qstarts) else n
            b = min(b, e)
            if b > a:
                cell = ch1[a:b]
                out[a:b] = 1 if cell.sum() * 2 >= cell.size else 0
            j += 1
    return out


def packet_windows(ch0, spb, preamble_bytes=DEFAULT_PREAMBLE_BYTES,
                   margin_bits=2.0):
    """GDO0 sync-strobe pulses -> (start, end) sample windows, one per packet.

    GDO0 is the CC1101 sync strobe (GDO_CFG=0x06): it rises when the sync word
    has been received, i.e. at the end of the preamble+sync region, so a rise
    anchors the packet.  Backfill preamble+sync before the rise and the payload
    after it (plus a margin).  GDO2 (async serial, GDO_CFG=0x0D) keeps toggling
    on demodulator noise between bursts; these windows cut that tail out.
    """
    pre_len = preamble_bytes * 8
    sync_len = len(SYNC_BITS)
    pre_s = round((pre_len + sync_len) * spb)
    pay_s = round(32 * spb)
    m = round(margin_bits * spb)
    rises = np.flatnonzero(np.diff(ch0.astype(np.int8)) == 1)
    windows = []
    for rise in rises:
        start = max(0, rise - pre_s - m)
        end = min(len(ch0), rise + pay_s + m)
        if end - start >= pay_s:
            windows.append((int(start), int(end)))
    return windows


def detect_datarate(ch1, rate, windows, glitch=10):
    """Estimate samples-per-bit (and bps) from the GDO0-gated packet windows.

    The alternating 0xAA preamble produces single-bit cells of length ~spb;
    the median of those run lengths is robust even when glitch removal merged
    a few cells.  Returns (spb, bps) or (None, None) when nothing to measure.
    """
    seed = rate / BPS
    cells = []
    for s, e in windows:
        for _lvl, ln in rl_encode(remove_glitches(ch1[s:e], glitch)):
            if round(ln / seed) == 1:
                cells.append(ln)
    if not cells:
        return None, None
    spb = float(np.median(cells))
    return spb, rate / spb


def detect_datarate_iter(ch0, ch1, rate, seed_spb,
                         preamble_bytes=DEFAULT_PREAMBLE_BYTES, glitch=10,
                         iters=3):
    """Gate -> measure datarate -> re-gate with the measured spb, iterated.

    The GDO0 backfill uses the seed spb; if the real datarate differs from the
    nominal 2400 bps the window is offset by (pre+sync) * |seed-actual|.  One
    iteration re-gates with the measured spb so the window lands precisely.
    Returns (spb, bps, windows).
    """
    spb = seed_spb
    windows = []
    for _ in range(iters):
        windows = packet_windows(ch0, spb, preamble_bytes)
        d_spb, _ = detect_datarate(ch1, rate, windows, glitch)
        if d_spb is None or abs(d_spb - spb) < 0.1:
            break
        spb = d_spb
    return spb, rate / spb, windows


def packet_anchors(ch0, spb, preamble_bytes=DEFAULT_PREAMBLE_BYTES):
    """Sample start of each packet from GDO0 sync-strobe rises.

    GDO0 rises when the sync word has been received (end of preamble+sync), so
    preamble start = rise - (preamble+sync)*spb, accurate to ~1 sample.
    """
    pre_len = preamble_bytes * 8
    sync_len = len(SYNC_BITS)
    rises = np.flatnonzero(np.diff(ch0.astype(np.int8)) == 1) + 1
    return [int(round(rise - (pre_len + sync_len) * spb)) for rise in rises]


def packet_starts(ch0, spb, packets, preamble_bytes=DEFAULT_PREAMBLE_BYTES):
    """Sample start of each decoded packet, anchored on its GDO0 rise.

    The decoded bit offset can drift many bits because it is quantized from a
    run-length encoding of the (noisy) GDO2 stream; the GDO0 strobe gives the
    exact sync-match sample (rise - (preamble+sync)*spb, ~1 sample accurate).
    Each GDO0 pulse maps to exactly one packet and both are time-ordered, so
    when the counts match the k-th packet is anchored on the k-th rise.
    """
    anchors = packet_anchors(ch0, spb, preamble_bytes)
    if len(anchors) == len(packets):
        return [int(a) for a in anchors]
    starts = []
    for p in packets:
        est = p["offset_bits"] * spb
        best, bd = 0, abs(anchors[0] - est)
        for j, a in enumerate(anchors):
            d = abs(a - est)
            if d < bd:
                best, bd = j, d
        starts.append(int(round(anchors[best])))
    return starts


def bits_expect(data):
    """MSB-first bit array of a byte sequence (the expected payload)."""
    return bits_msb(data)


def find_packets(bitseq, spb, preamble_bytes=DEFAULT_PREAMBLE_BYTES,
                 payload_expect=PAYLOAD_EXPECT):
    sync_len = len(SYNC_BITS)
    pre_len = preamble_bytes * 8
    exp_bits = bits_expect(payload_expect)
    packets = []
    i = 0
    while i < len(bitseq) - sync_len:
        if (bitseq[i:i + sync_len] == SYNC_BITS).all():
            if i + sync_len + 32 > len(bitseq):
                break
            start = i - pre_len
            window = bitseq[start:i] if start >= 0 else np.array([], dtype=np.uint8)
            pre_ok = preamble_ok(window, pre_len)
            payload_bits = bitseq[i + sync_len:i + sync_len + 32]
            payload = bytes(
                int("".join(str(b) for b in payload_bits[j:j + 8]), 2)
                for j in range(0, 32, 8)
            )
            errors = 0
            if len(payload) == 4 and len(exp_bits) == 32:
                errors = int(np.count_nonzero(payload_bits != exp_bits))
            packets.append(
                {
                    "offset_bits": int(start),
                    "preamble_ok": pre_ok,
                    "sync": True,
                    "payload": payload,
                    "bit_errors": errors,
                }
            )
            i += sync_len
        else:
            i += 1
    return packets


def find_packets_multiphase(ch, spb, sync_tol=3, payload_expect=PAYLOAD_EXPECT,
                            preamble_bytes=DEFAULT_PREAMBLE_BYTES, rate=None):
    """Phase-swept sync search over the raw GDO2 async-demod stream.

    The CC1101 re-acquires bit-sync at a different phase per packet after each
    inter-burst gap, so a single fixed sampling phase (find_packets) misses
    most packets.  This sweeps every phase of the samples-per-bit grid,
    sampling one bit per cell directly from the raw samples (no glitch filter,
    no run quantization), and scans each phase stream for the TX sync word
    0xBEEF (gen_2fsk.py) with a bit-error tolerance.

    Returns one representative per distinct packet (deduped across phases by
    sync-start sample, keeping the lowest (sync_errors, bit_errors)); noise
    matches are dropped unless the sync is perfect.  Each dict carries the
    legacy find_packets keys (offset_bits, preamble_ok, sync, payload,
    bit_errors) plus the multi-phase report keys (phase, sync_errors,
    timestamp_s, sync_start).

    offset_bits is the preamble-start bit index on the ~1-bit-per-spb
    quantized grid (round(sync_start/spb) - preamble*8), so packet_starts /
    refine_packets / clean_gdo2 keep working unchanged.
    """
    ch = np.asarray(ch, dtype=np.uint8)
    spbi = max(1, int(round(spb)))
    sync_len = len(MP_SYNC_BITS)
    exp_bits = bits_expect(payload_expect)
    pay_len = len(exp_bits)
    pre_len = preamble_bytes * 8
    view = np.lib.stride_tricks.sliding_window_view
    hits = []
    for phase in range(spbi):
        b = ch[phase::spbi]
        if len(b) <= sync_len + pay_len:
            continue
        dist = np.count_nonzero(view(b, sync_len) != MP_SYNC_BITS, axis=1)
        for i in np.flatnonzero(dist <= sync_tol):
            j = i + sync_len + pay_len
            if j > len(b):
                continue
            pay_bits = b[i + sync_len:j]
            pay_err = int(np.count_nonzero(pay_bits != exp_bits))
            hits.append((int(i * spbi + phase), phase, int(dist[i]), pay_err,
                         bytes_from_bits(pay_bits)))
    if not hits:
        return []
    hits.sort(key=lambda h: h[0])
    groups = []
    for h in hits:
        if groups and h[0] - groups[-1][-1][0] <= spbi:
            groups[-1].append(h)
        else:
            groups.append([h])
    packets = []
    for sync_start, phase, sync_err, pay_err, payload in (
            min(g, key=lambda h: (h[2], h[3])) for g in groups):
        if sync_err and pay_err > 2:
            continue
        b = ch[phase::spbi]
        i = (sync_start - phase) // spbi
        window = b[i - pre_len:i] if i >= pre_len else np.array([], np.uint8)
        d = {
            "offset_bits": i - pre_len,
            "preamble_ok": preamble_ok(window, pre_len),
            "sync": True,
            "payload": payload,
            "bit_errors": pay_err,
            "phase": phase,
            "sync_errors": sync_err,
            "sync_start": sync_start,
        }
        if rate:
            d["timestamp_s"] = sync_start / rate
        packets.append(d)
    packets.sort(key=lambda p: p["sync_start"])
    return packets


def retime_bits(bits, target_len, start, spb):
    """Render a bit sequence as a clean NRZ signal: bit k occupies exactly spb
    samples starting at start + round(k*spb); the rest stays 0."""
    out = np.zeros(target_len, dtype=np.uint8)
    if start < 0:
        return out
    for k, b in enumerate(bits):
        a = round(start + k * spb)
        c = round(start + (k + 1) * spb)
        if a >= target_len:
            break
        out[a:min(c, target_len)] = b
    return out


def uart_encode_bytes(data):
    """Async UART frames (start bit, 8 data bits MSB-first, stop bit) for a
    byte sequence: [0 d7 d6 d5 d4 d3 d2 d1 d0 1] per byte."""
    bits = []
    for b in data:
        bits.append(0)
        bits.extend((b >> (7 - k)) & 1 for k in range(8))
        bits.append(1)
    return np.asarray(bits, dtype=np.uint8)


def clean_gdo2(packets, starts, spb, preamble_bytes, target_len, framed=False,
               corrected=False, sync_bytes=SYNC_BYTES):
    """Noise-gated reconstruction of GDO2 from the decoded packet data.

    GDO2 is the raw async-serial demodulator output: it carries sub-bit
    glitches, bit-sync settling artifacts at the start of a burst and a noise
    tail between bursts (no carrier -> the demodulator toggles freely).  This
    rebuilds the byte stream the radio intended from the decoded packets
    (`refine_packets`) and places it at the actual received-cell start
    (`starts`), with the line idle (high) everywhere else.

    Two modes:
    - framed=True: async UART frames (start bit, 8 data bits MSB-first, stop
      bit) of the preamble + sync + payload bytes, so a stock 2400-baud UART
      decoder reads the exact packet bytes.  This is the recommended / emitted
      channel (`GDO2_CLEAN`): the falling start-bit edge marks the burst start
      unambiguously and the 0xAA preamble (which is phase-ambiguous to an
      async UART decoder when raw) decodes exactly.  Its burst is 25% longer
      than the radio signal - inherent to the start/stop framing.  With
      `corrected=True` the sync and payload bytes are taken from the
      error-corrected received bits (`p["pbits"]` from refine_packets, i.e.
      the majority-vote of the actual demod cells) instead of the ideal
      SYNC_BYTES/decoded payload; the preamble stays the ideal 0xAA because
      the modem bit-sync settles over the leading bits and they cannot be
      decoded faithfully.  That is the `GDO2_CLEAN_RAW` channel: UART-framed,
      still anchored on the received bits, decoding to the same packet.
    - framed=False: clean NRZ of the exact radio bits (preamble + sync +
      payload), one `int(spb)` sample per bit - the same bit count and width
      as the FSK render.  Kept only as a code option (it is redundant with
      the FSK analog channel and has no visible start marker, since the first
      preamble bit is high like the idle line); not emitted to the .sr/.vcd.

    Provenance: the payload bytes are the majority-vote decode of the actual
    GDO2 sample cells (refine_packets); the bit timing is the run-derived
    edge start.  The preamble (0xAA x preamble_bytes) and sync word
    (SYNC_BYTES) are taken from the known TX configuration - they cannot be
    decoded from the raw stream because the modem bit-sync settles over the
    leading bits and the 0xAA preamble is phase-ambiguous to an async UART
    decoder (it locks an even number of bits off the true byte boundary and
    then misreads the payload).
    """
    m = int(spb)
    out = np.full(target_len, 1, dtype=np.uint8)
    for p, start in zip(packets, starts):
        payload = bytes(p["payload"])
        if framed:
            if corrected:
                pb = p.get("pbits")
                if pb is not None:
                    pre_len = preamble_bytes * 8
                    sync_len = len(sync_bytes) * 8
                    sync_bytes_rx = bytes_from_bits(pb[pre_len:pre_len + sync_len])
                    pay_bytes = bytes_from_bits(pb[pre_len + sync_len:])
                    data = bytes([0xAA]) * preamble_bytes + sync_bytes_rx + pay_bytes
                else:
                    data = bytes([0xAA]) * preamble_bytes + sync_bytes + payload
            else:
                data = bytes([0xAA]) * preamble_bytes + sync_bytes + payload
            bits = uart_encode_bytes(data)
        else:
            bits = np.concatenate([
                preamble_bits(preamble_bytes),
                bits_msb(sync_bytes),
                bits_msb(payload),
            ])
        if start < 0:
            continue
        for k, b in enumerate(bits):
            a = start + k * m
            if a >= target_len:
                break
            out[a:min(a + m, target_len)] = b
    return out


def refine_packets(ch1, spb, packets, starts, preamble_bytes,
                   payload_expect=PAYLOAD_EXPECT, sync_bits=SYNC_BITS):
    """Re-decode each packet's bits by majority vote over the received cells.

    find_packets locates the sync in the run-length-quantized stream, which
    absorbs the bit-sync settling at burst start and the cell jitter.  The
    sample-accurate bit grid is recovered from the raw GDO2 edges: each bit
    cell spans [run-derived start, next run-derived start), re-synced at every
    run boundary, so a uniform anchor-based grid (e.g. GDO0 rise minus the
    nominal packet length) is NOT used - the demod compresses the early bits
    and that grid lands ~0.5-1 bit off the real data.  Each cell is then
    majority-voted so sub-bit glitches cannot flip it.

    Returns (packets, grid_starts): packets get exact payloads and the
    error-corrected full-packet bits (`p["pbits"]`, preamble + sync + payload);
    grid_starts are the sample positions of each packet's first bit (used to
    place the clean GDO2 channel in line with the raw demod edges, while the
    GDO0 `starts` remain the reference for the analog FSK render).
    """
    pre_len = preamble_bytes * 8
    sync_len = len(sync_bits)
    nbits = pre_len + sync_len + 32
    runs = rl_encode(remove_glitches(ch1, 10))
    qbits, qstarts = runs_to_bits_pos(runs, spb)
    grid_starts = []
    for p in packets:
        j0 = p["offset_bits"]
        pbits = np.empty(nbits, dtype=np.uint8)
        for k in range(nbits):
            j = j0 + k
            a = int(qstarts[j]) if 0 <= j < len(qstarts) else 0
            b = int(qstarts[j + 1]) if 0 <= j + 1 < len(qstarts) else round(a + spb)
            cell = ch1[a:b]
            pbits[k] = 1 if cell.size and cell.sum() * 2 >= cell.size else 0
        payload_bits = pbits[pre_len + sync_len:]
        payload = bytes(
            int("".join(str(b) for b in payload_bits[j:j + 8]), 2)
            for j in range(0, 32, 8)
        )
        errors = int(np.count_nonzero(payload_bits != bits_expect(payload_expect)))
        if (pbits[pre_len:pre_len + sync_len] != sync_bits).any():
            # Voted grid lost the sync (a glitch dropped a quantized bit and
            # shifted the cell mapping); fall back to the find_packets decode.
            payload = p["payload"]
            errors = p["bit_errors"]
            pbits = np.concatenate([
                preamble_bits(preamble_bytes),
                sync_bits,
                bits_msb(payload),
            ])
        p["payload"] = payload
        p["bit_errors"] = errors
        p["pbits"] = pbits
        grid_starts.append(int(qstarts[j0]) if 0 <= j0 < len(qstarts) else 0)
    return packets, grid_starts


def modulate(bits, dev, amp, sps=SPS):
    total = len(bits) * sps
    iq = np.empty(total, dtype=np.complex64)
    phase = 0.0
    k = 0
    for b in bits:
        f = dev if b else -dev
        dphi = 2.0 * np.pi * f / FS
        for _ in range(sps):
            iq[k] = amp * np.exp(1j * phase)
            phase += dphi
            k += 1
    return iq


def write_c8(path, iq):
    full = np.stack((np.real(iq), np.imag(iq)), axis=-1).astype(np.int8)
    full.tofile(path)
    return full


def common_args(ap):
    ap.add_argument("--raw", required=True, help="capture .raw file")
    ap.add_argument("--rate", type=int, default=48000,
                    help="requested capture rate (default 48000)")
    ap.add_argument("--spb", type=float, default=0.0,
                    help="samples per bit (default: derived from actual rate)")
    ap.add_argument("--glitch", type=int, default=10,
                    help="glitch run threshold in samples (default 10)")
    ap.add_argument("--preamble", type=int, default=DEFAULT_PREAMBLE_BYTES,
                    help="preamble bytes in the TX signal (default 4)")
    ap.add_argument("--payload-expect", type=str, default=None,
                    help="expected payload hex used for bit_errors/OK reporting "
                         "(default 01020304)")


def _payload_expect(args):
    """Parse --payload-expect into bytes (default PAYLOAD_EXPECT)."""
    if getattr(args, "payload_expect", None):
        try:
            return bytes.fromhex(args.payload_expect)
        except ValueError:
            sys.exit(f"error: invalid --payload-expect hex {args.payload_expect!r}")
    return PAYLOAD_EXPECT


def cmd_decode(args):
    pexpect = _payload_expect(args)
    ch0, ch1, rate = load_raw(args.raw, args.rate)
    seed = args.spb or (rate / BPS)
    spb, bps = seed, rate / seed
    if not args.spb:
        spb, bps, _ = detect_datarate_iter(ch0, ch1, rate, seed, args.preamble,
                                           args.glitch)
    bits = clean_bits(ch1, spb, args.glitch)
    packets = find_packets(bits, spb, args.preamble, pexpect)
    starts = packet_starts(ch0, spb, packets, args.preamble)
    packets, _ = refine_packets(ch1, spb, packets, starts, args.preamble,
                                pexpect)
    print(f"rate_actual={rate:.1f} Hz spb={spb:.3f} bps={bps:.0f} "
          f"samples={len(ch1)} bits={len(bits)} packets={len(packets)}")
    report = packets if not args.max else packets[:args.max]
    for p in report:
        flag = "OK " if p["preamble_ok"] and not p["bit_errors"] else "!! "
        hexp = " ".join(f"{b:02X}" for b in p["payload"])
        print(f"{flag}bit@{p['offset_bits']:>7} pre={'Y' if p['preamble_ok'] else 'N'} "
              f"errors={p['bit_errors']} payload={hexp}")
    good = sum(1 for p in packets if p["preamble_ok"] and not p["bit_errors"])
    payload_ok = sum(1 for p in packets if not p["bit_errors"])
    print(f"clean_packets={good}/{len(packets)} payload_ok={payload_ok}/{len(packets)}")
    return packets


def cmd_clean(args):
    """Error-correct the raw GDO2 signal (same length, no re-encode) and report
    the before/after decode quality: glitch filter + edge-resynced cells +
    majority vote + noise-tail gating (see clean_raw_gdo2).  Also writes a
    `<base>_clean.raw` (bit0=GDO0, bit1=corrected GDO2) for comparison."""
    pexpect = _payload_expect(args)
    ch0, ch1, rate = load_raw(args.raw, args.rate)
    seed = args.spb or (rate / BPS)
    spb, bps, windows = detect_datarate_iter(ch0, ch1, rate, seed,
                                             args.preamble, args.glitch)
    ch1c = clean_raw_gdo2(ch1, spb, windows, args.glitch)
    ntrans_raw = int(np.count_nonzero(ch1[1:] != ch1[:-1]))
    ntrans_cln = int(np.count_nonzero(ch1c[1:] != ch1c[:-1]))
    nsamp = len(ch1)
    active = sum(e - s for s, e in windows)
    print(f"rate={rate:.1f} Hz spb={spb:.3f} bps={bps:.0f} "
          f"samples={nsamp} windows={len(windows)} active={active} "
          f"({100.0 * active / nsamp:.1f}% of window)")

    def decode(ch):
        bits = clean_bits(np.asarray(ch, np.uint8), spb, args.glitch)
        packets = find_packets(bits, spb, args.preamble, pexpect)
        starts = packet_starts(ch0, spb, packets, args.preamble)
        packets, _ = refine_packets(np.asarray(ch, np.uint8), spb, packets,
                                    starts, args.preamble, pexpect)
        return packets

    raw_pk = decode(ch1)
    cln_pk = decode(ch1c)
    for label, pk in (("raw", raw_pk), ("clean_raw", cln_pk)):
        err = sum(p["bit_errors"] for p in pk)
        good = sum(1 for p in pk if p["preamble_ok"] and not p["bit_errors"])
        print(f"{label:9s} packets={len(pk)} payload_ok={good}/{len(pk)} "
              f"bit_errors={err}")
    print(f"transitions raw={ntrans_raw} clean_raw={ntrans_cln} "
          f"(-{100.0 * (ntrans_raw - ntrans_cln) / max(ntrans_raw, 1):.0f}%)")
    if cln_pk:
        payloads = " ".join("".join(f"{b:02X}" for b in p["payload"])
                            for p in cln_pk)
        print(f"clean_raw payloads: {payloads}")
    out = args.out or (args.raw.rsplit(".raw", 1)[0] + "_clean.raw")
    with open(out, "wb") as f:
        for a, b in zip(ch0, ch1c):
            f.write(bytes([(a & 1) | ((b & 1) << 1)]))
    print(f"wrote {out}")
    return cln_pk


def cmd_regen(args):
    pexpect = _payload_expect(args)
    ch0, ch1, rate = load_raw(args.raw, args.rate)
    spb = args.spb or (rate / BPS)
    bps = rate / spb
    packets = find_packets_multiphase(ch1, spb, payload_expect=pexpect,
                                      preamble_bytes=args.preamble)
    if not packets:
        sys.exit("error: no packets decoded, nothing to regenerate")
    starts = packet_starts(ch0, spb, packets, args.preamble)

    pre_len = args.preamble * 8
    pkt_bits = pre_len + len(MP_SYNC_BITS) + 32
    sps = int(round(FS / bps))
    full_n = round(len(ch1) / rate * FS)
    iq = np.zeros(full_n, dtype=np.complex64)
    placed = 0
    for p, start_sample in zip(packets, starts):
        block = np.concatenate([
            preamble_bits(args.preamble),
            MP_SYNC_BITS,
            bits_msb(p["payload"]),
        ])
        start = round(start_sample / rate * FS)
        end = start + len(block) * sps
        if 0 <= start and end <= full_n:
            iq[start:end] = modulate(block, args.dev, args.amp, sps)
            # Extend the last bit one sample so a phase-rotation demodulator
            # can measure the final bit cell (N samples only yield N-1 windows).
            if end < full_n:
                f = args.dev if block[-1] else -args.dev
                iq[end] = iq[end - 1] * np.exp(1j * 2.0 * np.pi * f / FS)
            placed += 1
    full = write_c8(args.out, iq)
    iq_i = np.stack((np.real(iq), np.zeros_like(np.real(iq))),
                    axis=-1).astype(np.int8)
    i_out = args.out.replace(".c8", "_i.c8")
    iq_i.tofile(i_out)
    dur = full_n / FS
    print(f"rate_actual={rate:.1f} Hz bps_det={bps:.0f} sps={sps} "
          f"packets={placed}/{len(packets)} bits/pkt={pkt_bits} "
          f"samples={full_n} dur={dur:.2f}s amp={args.amp} dev={args.dev}")
    print(f"wrote {args.out} ({full.nbytes / 1e6:.1f} MB)")
    print(f"wrote {i_out} ({iq_i.nbytes / 1e6:.1f} MB)")


def cmd_manual(args):
    """Decode one packet directly from the raw samples (majority vote per bit
    cell) and print every bit with its sample range so it can be verified
    by hand against the GDO2 waveform in PulseView."""
    ch0, ch1, rate = load_raw(args.raw, args.rate)
    spb = args.spb or (rate / BPS)
    if not args.spb:
        spb, _, _ = detect_datarate_iter(ch0, ch1, rate, spb, args.preamble,
                                         args.glitch)
    cleaned = remove_glitches(ch1, args.glitch)
    bits, starts = runs_to_bits_pos(rl_encode(cleaned), spb)
    packets = find_packets(bits, spb, args.preamble, _payload_expect(args))
    if not packets:
        sys.exit("error: no packets to decode manually")
    p = packets[0]
    npreamble = args.preamble * 8
    nsync = len(SYNC_BITS)
    nbits = npreamble + nsync + 32

    sync_exp = np.concatenate([SYNC_BITS, bits_msb(PAYLOAD_EXPECT)])

    # Anchor the bit grid on the sync word (the reliable, deterministic part):
    # run-length quantization can shift the preamble estimate by a bit, so
    # refine the sync start sample over +/- 2 bit cells.
    s_sync_est = int(starts[p["offset_bits"] + npreamble])
    csum = np.concatenate(([0], np.cumsum(cleaned, dtype=np.int64)))
    ks = np.arange(len(sync_exp) + 1, dtype=np.float64)
    half = int(2 * spb)
    best = (len(sync_exp) + 1, s_sync_est)
    lo = max(0, s_sync_est - half)
    hi = min(len(cleaned) - len(sync_exp) * spb, s_sync_est + half + 1)
    for s0 in range(lo, hi):
        b = np.round(s0 + ks * spb).astype(np.int64)
        sums = csum[b[1:]] - csum[b[:-1]]
        dec = (sums * 2 >= (b[1:] - b[:-1])).astype(np.uint8)
        err = int(np.count_nonzero(dec != sync_exp))
        if err < best[0]:
            best = (err, s0)
    s_sync = best[1]
    s_pre = round(s_sync - npreamble * spb)

    pre = majority_bits(cleaned, s_pre, npreamble, spb)
    syn = majority_bits(cleaned, s_sync, len(sync_exp), spb)
    dec = np.concatenate([pre, syn])
    full_exp = np.concatenate([preamble_bits(args.preamble), sync_exp])

    print(f"rate_actual={rate:.1f} Hz spb={spb:.3f}")
    print(f"packet bit@{p['offset_bits']} -> preamble @ sample {s_pre}, "
          f"sync @ {s_sync}, {nbits} bits / {round(nbits * spb)} samples")

    print(f"{'idx':>4} {'samples':>16}  bit exp  match   cell 0/1 ratio")
    for k in range(nbits):
        a = round(s_pre + k * spb)
        b = round(s_pre + (k + 1) * spb)
        cell = cleaned[a:b]
        ratio = f"{int(cell.sum()):>3}/{len(cell):<3}"
        mark = "*" if dec[k] == full_exp[k] else "MISMATCH"
        print(f"{k:>4} {a:>8}..{b:<8}  {dec[k]}  {full_exp[k]}    "
              f"{mark:<8} {ratio}")

    s = "".join(str(x) for x in dec)
    pre_s = " ".join(s[i:i + 8] for i in range(0, npreamble, 8))
    pre_hex = " ".join(f"{int(s[i:i + 8], 2):02X}"
                       for i in range(0, npreamble, 8))
    sync_hex = "".join(str(x) for x in dec[npreamble:npreamble + nsync])
    pay_s = " ".join(s[npreamble + nsync:][i:i + 8] for i in range(0, 32, 8))
    pay_hex = " ".join(f"{int(s[npreamble + nsync:][i:i + 8], 2):02X}"
                       for i in range(0, 32, 8))

    print("\nbyte view (MSB-first, read left->right as in the waveform):")
    print(f"  preamble {' ' + pre_s}  (captured {pre_hex}; "
          f"TX sends {' '.join(['AA'] * args.preamble)})")
    print(f"  sync     1101 1110 1010 1111  (DE AF)")
    print(f"  payload  {pay_s}  ({pay_hex})")

    sync_ok = int(np.count_nonzero(
        dec[npreamble:npreamble + nsync] != SYNC_BITS)) == 0
    pay_ok = int(np.count_nonzero(
        dec[npreamble + nsync:] != bits_msb(PAYLOAD_EXPECT))) == 0
    print(f"MANUAL: sync {'DE AF OK' if sync_ok else 'MISMATCH'}, "
          f"payload {'01 02 03 04 OK' if pay_ok else 'MISMATCH'}, "
          f"preamble captured {pre_hex}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    d = sub.add_parser("decode", help="decode GDO2 capture into packets")
    common_args(d)
    d.add_argument("--max", type=int, default=0, help="max packets to report")
    d.set_defaults(func=cmd_decode)

    r = sub.add_parser("regen", help="re-modulate decoded packets to 2FSK I/Q")
    common_args(r)
    r.add_argument("--out", required=True, help="output .c8 file")
    r.add_argument("--amp", type=int, default=DEFAULT_AMP)
    r.add_argument("--dev", type=float, default=DEFAULT_DEV)
    r.set_defaults(func=cmd_regen)

    m = sub.add_parser("manual", help="decode a packet bit-by-bit from the "
                                      "raw samples for hand verification")
    common_args(m)
    m.set_defaults(func=cmd_manual)

    c = sub.add_parser("clean", help="error-correct the raw GDO2 signal "
                                     "(glitch filter + edge resync + majority "
                                     "vote + noise gating) and report "
                                     "before/after decode quality")
    common_args(c)
    c.add_argument("--out", default=None, help="output <base>_clean.raw")
    c.set_defaults(func=cmd_clean)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
